services:

# ======================= BACKEND =======================

  backend:
    build:
      context: ./backend/core-api
    restart: always
    volumes:
      - ./storage:/backend/core-api/storage

    environment:

      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: main

      SECRET_KEY: your_super_secret_key # Change me
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

      # LOG_LEVEL: INFO
      # API_HOST: 0.0.0.0
      # API_PORT: 8000
      # RELOAD: true
      # UVICORN_LOG_LEVEL: info

    expose: 
      - 8000
    networks: 
      - app-network
    depends_on:
      - postgres

# ======================= FRONTEND =======================

  frontend:
    build: 
      context: ./frontend
      target: dev
    restart: always
    environment:

      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:3000/ws

    expose:
      - 5173
    networks:
      - app-network
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
      - realtime

# ======================= REALTIME =======================

  realtime:
    build: 
      context: ./backend/realtime-service
      target: dev
    restart: always
    environment:
      
      WS_PORT: 3000
      CORE_API_URL: http://backend:8000

    expose:
      - 3000
    networks:
      - app-network
    volumes:
      - ./backend/realtime-service:/backend/realtime-service
      - /backend/realtime-service/node_modules

# ======================= DATABASE =======================

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - app-network

# ======================= NGINX ==========================

  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:8000
      - 3000:3000
      - 1337:1337
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      - realtime

# ======================= NETWORKS =======================

networks:
  app-network:
    driver: bridge