global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: app_name
        replacement: "messenger-backend"
