import {
  Loader2,
  User,
  Lock,
  AlertCircle,
  X,
  CheckCircle2,
  AlertTriangle,
  Info,
  Settings,
  SendHorizontal,
  FilePlus,
  CircleCheck,
  ChevronLeft,
  ChevronRight,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  user: User,
  lock: Lock,
  alertCircle: AlertCircle,
  x: X,
  checkCircle: CheckCircle2,
  warning: AlertTriangle,
  info: Info,
  settings: Settings,
  send: SendHorizontal,
  filePlus: FilePlus,
  check: CircleCheck,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  file: File,
  fileText: FileText,
  fileImage: FileImage,
  fileVideo: FileVideo,
  fileAudio: FileAudio,
  fileArchive: FileArchive,
};
